backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/AbsoluteCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/BookCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/CategoryCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/Coupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/CouponType.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/RelativeCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/Target.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/UserCoupon.java

closes #3 
- Builder 추가
- local 실행 시 로그 확인
- #61 Builder만 추가 후 다시 올림

[#3][BACK][쿠폰][Entity] - 쿠폰 Entity 생성

---

backend-server/pom.xml
backend-server/src/main/java/shop/bluebooktle/backend/BackendServerApplication.java
backend-server/src/main/java/shop/bluebooktle/backend/user/repository/AddressRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/user/repository/MembershipLevelRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/user/repository/UserRepository.java
backend-server/src/main/resources/ddl.sql
backend-server/src/main/resources/project.md
common-module/pom.xml
common-module/src/main/java/shop/bluebooktle/common/dto/request/SignupRequestDto.java
common-module/src/main/java/shop/bluebooktle/common/entity/Address.java
common-module/src/main/java/shop/bluebooktle/common/entity/MembershipLevel.java
common-module/src/main/java/shop/bluebooktle/common/entity/User.java
gateway-server/pom.xml
pom.xml

- refs #28 
- User, Address, MembershipLevel Entity 공통 모듈로 이동
- Auth와 Back 서버에서 공통으로 사용하는 Entity Common으로 이동했습니다. 
- MSA 구조는 아니지만 db 공유하는 상황에서 통신으로 처리하는 건 과한 작업인 것 같아 entity 공유하는 방식으로 작업하려 합니다. 
- 다른 작업 진행을 위해 해당 영역 우선 Pr 올립니다. 
-

[#28][BACK, COMMON][회원] - 상세 설명 User, Address, MembershipLevel Entity 공통 모듈로 이동

---

frontend-server/src/main/resources/application-dev.yml
frontend-server/src/main/resources/application-local.yml
frontend-server/src/main/resources/application-prod.yml

- frontend-server port변경 및 yml 위치 resources로 이동
-
-
-

[FRONT]refatctor: frontend-server port변경 및 yml 위치 resources로 이동

---

pom.xml

- ci  중 auth-server 모듈이 없다는 오류가 발생되어 해당 모듈 주석
-
-
-

[INFRA][CICD] refactor: ci-auth server module 주석

---

.github/workflows/pr_webhook.yml

-  PR 알림 Workflow 추가
- PR 생성시 dooray에 알림을 보냅니다. 
-

[][WORKFLOW][PR 알림] - PR 알림 Workflow 추가

---

backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Author.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Book.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookAuthor.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookImg.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookLikes.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookLikesId.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookPublisher.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookSaleInfo.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookTag.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Img.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Publisher.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Tag.java

refs https://github.com/nhnacademy-be9-bluebooktle/bluebooktle-shop/issues/51
- 인공키 변수 통일
- BookLikes 생성자 수정
- @SQLDelete, @SQLRestriction 추가
- 코드 컨벤션 적용
-
-
-

[#51][BACK][도서] - book 엔티티 수정

---

backend-server/src/main/resources/application-dev.yml
backend-server/src/main/resources/application-local.yml
backend-server/src/main/resources/application-prod.yml
backend-server/src/main/resources/application.yml
eureka-server/src/main/resources/application-dev.yml
eureka-server/src/main/resources/application-local.yml
eureka-server/src/main/resources/application-prod.yml
frontend-server/pom.xml
frontend-server/src/main/java/shop/bluebooktle/frontend/FrontendServerApplication.java
frontend-server/src/main/resources/application-dev.yml
frontend-server/src/main/resources/application-local.yml
frontend-server/src/main/resources/application-prod.yml
frontend-server/src/main/resources/application.properties
frontend-server/src/main/resources/application.yml
gateway-server/src/main/resources/application-local.yml
gateway-server/src/main/resources/application.yml

closes #82 
- 유레카 서버 및 클라이언드 등록
-
-
-

[#82][Infra][eureka] - 유레카 등록

---

backend-server/pom.xml
backend-server/src/main/java/shop/bluebooktle/backend/cart/dto/CartItemRequest.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/dto/CartItemResponse.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/helper/AuthContextHelper.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/repository/CartBookRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/repository/CartRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/service/CartService.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/service/impl/CartServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/config/RedisConfig.java

refs #43 
- Service + Impl 구현
- Repository 구현
- DTO 구현
- Redis Config 완료
- Controller 작업 위한 Base 작업 완료
- Redis Dependency pom.xml에 추가
-

[#43][BACK][장바구니][Class추가] Repository/Service/Dto/Redis 추가

---

backend-server/src/main/java/shop/bluebooktle/backend/cart/helper/AuthContextHelper.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/repository/CartRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/service/CartService.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/service/impl/CartServiceImpl.java

- user entity import 위치 수정
-
-
-

fix(user): user entity import 수정

---

backend-server/src/main/resources/schema.sql

refs #97 
- src/main/resources/schema.sql 파일 생성
- 테이블/제약조건 DDL 문을 schema.sql에 작성
- backend-server의 resources 하위 schema.sql 파일 추가됨

[#97][BACK][config] - JPA auto-ddl 설정용 schema.sql 리소스 추가

---

backend-server/http/coupon.http
backend-server/src/main/java/shop/bluebooktle/backend/coupon/controller/CouponController.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/controller/CouponTypeController.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/AbsoluteCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/BookCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/CategoryCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/Coupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/CouponType.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/RelativeCoupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/AbsoluteCouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/BookCouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CategoryCouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponTypeRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/RelativeCouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/CouponService.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/CouponTypeService.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/CouponServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/CouponTypeServiceImpl.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/request/CouponRegisterRequest.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/request/CouponTypeRegisterRequest.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/response/CouponResponse.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/response/CouponTypeResponse.java
common-module/src/main/java/shop/bluebooktle/common/exception/ErrorCode.java
common-module/src/main/java/shop/bluebooktle/common/exception/coupon/CouponNameAlreadyExistsException.java
common-module/src/main/java/shop/bluebooktle/common/exception/coupon/CouponTypeNameAlreadyException.java
common-module/src/main/java/shop/bluebooktle/common/exception/coupon/CouponTypeNotFoundException.java
common-module/src/main/java/shop/bluebooktle/common/exception/coupon/InvalidCouponTargetException.java

refs #4 
- 쿠폰 정책 등록, 조회 구현
- 쿠폰 등록, 조회 구현
- AbsoulteCoupon, BookCoupon, CategoryCoupon 생성자 추가
- coupon 테이블에 있는 minimum_payment 컬럼을 coupon_type으로 이동
- TODO 1. queryDSL 적용(@Query 제거)
- TODO 2. GlobalExceptionHandler 생성
minimum_payment
coupon 테이블 -> coupon_type 테이블 이동

[#4][BACK][쿠폰] - 쿠폰 정책 등록/조회, 쿠폰 등록/조회 개발

---

auth-server/src/main/java/shop/bluebooktle/auth/AuthServerApplication.java
common-module/src/main/java/shop/bluebooktle/common/exception/handler/GlobalExceptionHandler.java

closes #113 
- GlobalExceptionHandler를 common-module에 구현하여 전체 도메인에서 JSend 에러 포맷 적용
- auth-server에서 기존 AuthGlobalExceptionHandler 제거
- 추가설명 : backend-server나 front-server에서 GlobalExceptionHandler를 사용하고 싶다면 scanBasePackages 설정
- 이유 : @SpringBootApplication은 기본적으로 자기 자신이 속한 패키지와 그 하위만 @ComponentScan으로 스캔하기 때문
- auth-server에서 auth.http로 예외응답 확인

[#113][COMMON][예외처리][Handler] - GlobalExceptionHandler 위치 이동 및 스캔 범위 설정

---

.github/workflows/maven.yml
auth-server/src/main/resources/application-dev.yml
auth-server/src/main/resources/application-prod.yml
auth-server/src/main/resources/application.yml
backend-server/pom.xml
backend-server/src/main/resources/application-dev.yml
backend-server/src/main/resources/application-prod.yml
backend-server/src/main/resources/application.yml
eureka-server/pom.xml
eureka-server/src/main/resources/application-dev.yml
eureka-server/src/main/resources/application-prod.yml
eureka-server/src/main/resources/application.yml
frontend-server/pom.xml
frontend-server/src/main/resources/application-dev.yml
frontend-server/src/main/resources/application-prod.yml
frontend-server/src/main/resources/application.properties
frontend-server/src/main/resources/application.yml
gateway-server/pom.xml
gateway-server/src/main/resources/application-dev.yml
gateway-server/src/main/resources/application-prod.yml
gateway-server/src/main/resources/application.yml

closes #65 
-  모듈별, default, dev, prod 프로파일 Config Repository로 등록
- Config Server구축
- 각 모듈 Config Client로 변경
- blueBooktle.shop/config/모듈명/프로파일명 으로 확인할 수 있습니다
- https://github.com/nhnacademy-be9-bluebooktle/bluebooktle-docs/blob/main/Infra/Spring%20Cloud%20Config.md 의 하단 Client 부분 참고, 접근 id와 password는 두레이 메신저 공지
-
-

[#65][Infra][Config] - 설정 파일 외부 참조

---

backend-server/http/coupon.http
backend-server/src/main/java/shop/bluebooktle/backend/BackendServerApplication.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/controller/CouponController.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponTypeRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/CouponServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/CouponTypeServiceImpl.java

refs #4 
- repository에 임시 query문 수정 및 작성
- backendServerApplication에 ExceptionHandler 작동하도록 수정
- #106

[#4][BACK][쿠폰] - coupon 등록,조회 오류 수정

---

backend-server/http/coupon.http
backend-server/src/main/java/shop/bluebooktle/backend/coupon/controller/CouponController.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/Coupon.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/BookCouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CategoryCouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/CouponService.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/CouponServiceImpl.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/request/CouponUpdateRequest.java
common-module/src/main/java/shop/bluebooktle/common/exception/coupon/CouponNotFountException.java

closes #16 
- coupon 수정 삭제 기능 구현

[#16][BACK][쿠폰] - 쿠폰 수정, 삭제

---

auth-server/src/main/resources/application-local.yml
backend-server/src/main/resources/application-local.yml
eureka-server/pom.xml
eureka-server/src/main/java/shop/bluebooktle/eureka/config/SecurityConfig.java
frontend-server/src/main/resources/application-local.yml
gateway-server/src/main/resources/application-local.yml

유레카 서버에 접근시 인증 추가
-
- 유레카 접속시 인증창 뜨는지 확인
-
-

[BACK][EUREKA] - 유레카 security 추가

---

backend-server/src/main/java/shop/bluebooktle/backend/book/repository/AuthorRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookAuthorRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookImgRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookPublisherRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookTagRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/ImgRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/PublisherRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/TagRepository.java

refs #132 
- AuthorRepository
- PublisherRepository
- TagRepository
- ImgRepository
- BookAuthorRepository
- BookPublisherRepository
- BookTagRepository
- BookImgRepository
-
-
-

[#132][BACK][도서] - Repository 생성

---

backend-server/http/aladinApiTest.http
backend-server/src/main/java/shop/bluebooktle/backend/book/controller/AladinBookController.java
backend-server/src/main/java/shop/bluebooktle/backend/book/dto/request/AladinBookItem.java
backend-server/src/main/java/shop/bluebooktle/backend/book/dto/request/BookRegisterByAladinRequest.java
backend-server/src/main/java/shop/bluebooktle/backend/book/dto/response/AladinApiResponse.java
backend-server/src/main/java/shop/bluebooktle/backend/book/dto/response/AladinBookResponseDto.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/AuthorRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/ImgRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/PublisherRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/AladinBookService.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/AladinBookServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookRegisterServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/CategoryServiceImpl.java
common-module/src/main/java/shop/bluebooktle/common/exception/BookAlreadyExistsException.java
common-module/src/main/java/shop/bluebooktle/common/exception/ErrorCode.java

refs #90
- jsend형식에 맞게 코드수정
- 예외 처리 추가
-aladinapitest.http로 확인

[#90][BACK][도서] - 알라딘 API 도서등록, 오류 수정

---

frontend-server/src/main/java/shop/bluebooktle/frontend/controller/AuthController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/MyPageController.java
frontend-server/src/main/resources/static/css/reset.css
frontend-server/src/main/resources/static/css/styles.css
frontend-server/src/main/resources/templates/_fragments/footer.html
frontend-server/src/main/resources/templates/_fragments/header.html
frontend-server/src/main/resources/templates/_fragments/mypage_sidebar.html
frontend-server/src/main/resources/templates/_layouts/default_layout.html
frontend-server/src/main/resources/templates/auth/signup_form.html
frontend-server/src/main/resources/templates/book/book_detail.html
frontend-server/src/main/resources/templates/book/book_list.html
frontend-server/src/main/resources/templates/cart/cart.html
frontend-server/src/main/resources/templates/main.html
frontend-server/src/main/resources/templates/mypage/address_list.html
frontend-server/src/main/resources/templates/mypage/coupon_list.html
frontend-server/src/main/resources/templates/mypage/likes_list.html
frontend-server/src/main/resources/templates/mypage/order_detail.html
frontend-server/src/main/resources/templates/mypage/order_list.html
frontend-server/src/main/resources/templates/mypage/point_log.html
frontend-server/src/main/resources/templates/mypage/profile.html
frontend-server/src/main/resources/templates/mypage/review_list.html
frontend-server/src/main/resources/templates/order/checkout.html
frontend-server/src/main/resources/templates/order/complete.html

- refs #36
마이페이지(내정보, 주문, 주소,포인트, 쿠폰, 리뷰, 좋아요) UI 추가
- refs #101

[#36][FRONT][마이페이지] - 마이페이지(내정보, 주문, 주소,포인트, 쿠폰, 리뷰, 좋아요) UI 추가

---

backend-server/pom.xml
backend-server/src/main/java/shop/bluebooktle/backend/config/QueryDslConfig.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/dto/CouponSearchRequest.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponQueryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponTypeRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/impl/CouponQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/CouponServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/CouponTypeServiceImpl.java
common-module/pom.xml
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/response/CouponResponse.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/response/CouponTypeResponse.java

refs #4 
-  QueryDSL 설정 추가
- 쿠폰, 쿠폰정책 전체 조회에 기존 @Query 기반 JPQL을 QueryDSL로 리팩토링
- 설정 변경 사항 (pom.xml) [backend-server, common-module]
-- querydsl-jpa, querydsl-apt 의존성 추가
-> mvn clean compile 명령어 실행 추천
- HTTP Request - coupon.http 실행
-  #116 기존 전체 조회 코드

[#4][BACK][COMMON] - queryDSL 설정 및 coupon 조회 부분에 적용

---

backend-server/src/main/java/shop/bluebooktle/backend/book/controller/AladinBookController.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/AladinBookServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookRegisterServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/CategoryServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/repository/CartBookRepository.java
gateway-server/src/main/java/shop/bluebooktle/gateway/config/RouterConfig.java

Backend server run 실패 이유
- book.service의 Impl패키지가 다른 서비스에서는 impl로 import되고 있어 오류. 
- Impl -> impl로 패키지 명 변경
- CartBookRepository의  deleteAll 메서드가 jpa 키워드 쿼리와 충돌로 오류
- 주석 처리
- 실행을 해보자
-
-

[BACK][FIX] - backend-server run실패 수정

---

backend-server/src/main/java/shop/bluebooktle/backend/order/entity/Order.java
backend-server/src/main/java/shop/bluebooktle/backend/order/repository/OrderRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/order/repository/OrderStateRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/OrderService.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/impl/OrderServiceImpl.java
common-module/src/main/java/shop/bluebooktle/common/exception/order/OrderNotFoundException.java

refs #120 
- 마이페이지 내 주문 조회 및 주문 상태 변경 로직 추가
- OrderRepository, OrderService, OrderServiceImpl, Order(changeOrderState 함수 추가)
- 주문 생성 삭제 등 아직 해야함
-
-
-
-

[#120][BACK][주문] - 마이페이지 주문내역 조회 Repository, Service 작성

---

backend-server/src/main/java/shop/bluebooktle/backend/order/repository/OrderRepository.java

- Repository 문제나는 메서드 삭제
-
-
-

fix(OrderRepository) : 에러나는 메서드 삭제

---

.github/workflows/maven.yml
auth-server/src/main/java/shop/bluebooktle/auth/util/JwtUtil.java
auth-server/src/main/resources/data.sql

Reverts nhnacademy-be9-bluebooktle/bluebooktle-shop#172

Revert " [][AUTH][fix] - auth-server  dev환경에서 실행 실패 에러 해결 "

---

.github/workflows/maven.yml
auth-server/src/main/java/shop/bluebooktle/auth/util/JwtUtil.java

[이슈번호][WORKFLOW] - merge 시에만 Deploy하도록 변경 
-
-
-
-

[이슈번호][WORKFLOW] - merge 시에만 Deploy하도록 변경 

---

backend-server/http/deliveryRule.http
backend-server/src/main/java/shop/bluebooktle/backend/order/controller/DeliveryRuleController.java
backend-server/src/main/java/shop/bluebooktle/backend/order/dto/request/DeliveryRuleRequest.java
backend-server/src/main/java/shop/bluebooktle/backend/order/dto/response/DeliveryRuleResponse.java
backend-server/src/main/java/shop/bluebooktle/backend/order/repository/DeliveryRuleRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/order/repository/OrderRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/DeliveryRuleService.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/OrderService.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/impl/DeliveryRuleSerivceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/impl/DeliveryRuleServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/impl/OrderServiceImpl.java
common-module/src/main/java/shop/bluebooktle/common/exception/handler/GlobalExceptionHandler.java
common-module/src/main/java/shop/bluebooktle/common/exception/order/CannotDeleteDefaultPolicyException.java
common-module/src/main/java/shop/bluebooktle/common/exception/order/DeliveryRuleNotFoundException.java

refs #119 
- DeliveryRule Repsitory, Service, Controller 작성
- localhost:9009 dev 프로필 실행 후 http 요청 테스트 완료 (Test 코드 작성 TODO)
-
-
-

[#119][BACK][배송정책] - 배송 정책 CRUD 작업

---

.github/workflows/maven.yml
backend-server/http/payment.http
backend-server/src/main/java/shop/bluebooktle/backend/payment/controller/PaymentTypeController.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/dto/request/PaymentTypeRequest.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/dto/response/PaymentTypeResponse.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/entity/PaymentType.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/repository/PaymentTypeRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/service/PaymentTypeService.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/service/impl/PaymentTypeServiceImpl.java
common-module/src/main/java/shop/bluebooktle/common/exception/ErrorCode.java
common-module/src/main/java/shop/bluebooktle/common/exception/payment/PaymentTypeAlreadyExistException.java
common-module/src/main/java/shop/bluebooktle/common/exception/payment/PaymentTypeNotFoundException.java

refs #124 
결제수단 crud작성
-
backend-server모듈 -> http패키지 -> payment.http참고
-
-
-

[#124 ][BACK][PAYMENT] - PaymentType CRUD로직 추가

---

.github/workflows/maven.yml
auth-server/pom.xml
auth-server/src/main/java/shop/bluebooktle/auth/AuthServerApplication.java
auth-server/src/main/java/shop/bluebooktle/auth/config/SecurityConfig.java

[CICD][AUTH] - JWT secrets 누락 

---

.github/workflows/maven.yml
auth-server/src/main/java/shop/bluebooktle/auth/AuthServerApplication.java

[CI/CD][AUTH] - 테스트 코드 제거

---

backend-server/http/bookCategory.http
backend-server/http/book_category.http
backend-server/http/book_publisher.http
backend-server/http/book_tag.http
backend-server/src/main/java/shop/bluebooktle/backend/book/controller/CategoryController.java
backend-server/src/main/java/shop/bluebooktle/backend/book/dto/request/BookAllRegisterRequest.java
backend-server/src/main/java/shop/bluebooktle/backend/book/dto/request/BookImgRegisterRequest.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookCategory.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookPublisher.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Category.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookCategoryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookPublisherRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/BookTagRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/BookTagService.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookCategoryServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookImgServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookPublisherServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookRegisterServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookTagServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/CategoryServiceImpl.java
backend-server/src/main/resources/schema.sql
backend-server/src/test/java/shop/bluebooktle/backend/BookServiceApplicationTest.java
backend-server/src/test/java/shop/bluebooktle/backend/coupon/jpa/CouponRepositoryTest.java
common-module/src/main/java/shop/bluebooktle/common/exception/ErrorCode.java
common-module/src/main/java/shop/bluebooktle/common/exception/book/CategoryCannotDeleteRootException.java
common-module/src/main/java/shop/bluebooktle/common/exception/book/TagNotFoundException.java
frontend-server/src/main/resources/templates/admin/index.html

closes #206 
refs #211 
- 도서 출판사 HTTP 테스트
- 도서 태그 HTTP 테스트
- 도서 카테고리 HTTP 테스트
- ERD 필드 순서 변경 (출판사, 카테고리)
- 도서 등록 로직 변경 (관계 테이블에서 가져오도록)
-
-
-

[#211, #206][BACK][도서] - http 테스트 및 도서 관계 테이블 로직 변경 및 도서 등록

---

backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Publisher.java
backend-server/src/main/java/shop/bluebooktle/backend/book/entity/Tag.java
backend-server/src/test/java/shop/bluebooktle/backend/book/controller/BookSaleInfoControllerTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/controller/CategoryControllerTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/controller/PublisherControllerTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/controller/TagControllerTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/BookSaleInfoServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/PublisherServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/TagServiceTest.java
common-module/src/main/java/shop/bluebooktle/common/dto/book/request/PublisherRequest.java
common-module/src/main/java/shop/bluebooktle/common/dto/book/response/PublisherInfoResponse.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/admin/AdminBookController.java
frontend-server/src/main/resources/templates/admin/book/book_form.html

refs #248 #249 
- 출판사, 태그, 도서판매정보 컨트롤러, 서비스 테스트코드 작성
- 카테고리 컨트롤러 테스트코드 작성 
- 테스트코드로 확인

[#248#249][BACK][도서] - 출판사, 도서판매정보, 태그, 카테고리 테스트코드 작성

---

backend-server/src/main/java/shop/bluebooktle/backend/config/SecurityConfig.java
frontend-server/src/main/java/shop/bluebooktle/frontend/config/TossFeignConfig.java

[FRONT][FIX] - FIx feign client configuration

---

auth-server/src/main/resources/application-local.yml
backend-server/src/main/java/shop/bluebooktle/backend/book/controller/AuthorController.java
backend-server/src/main/java/shop/bluebooktle/backend/book/controller/CategoryController.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/AuthorQueryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/AuthorRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/CategoryQueryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/CategoryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/impl/AuthorQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/impl/CategoryQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/AuthorService.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/CategoryService.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/AuthorServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/CategoryServiceImpl.java
backend-server/src/main/resources/application-local.yml
common-module/src/main/java/shop/bluebooktle/common/dto/book/request/BookAllRegisterRequest.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/admin/AdminAuthorController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/AdminAuthorServiceImpl.java

closes #251 
closes #267 
- 검색 기능 구현 
-
-
-

[#251, #267][FRONT, BACK][도서] - 관리자 페이지 : 카테고리, 작가 검색 기능

---

.github/workflows/maven.yml
.github/workflows/pr-test.yml
backend-server/src/test/resources/application-test.yml

[FIX][CHORE] - fix maven.yml error

---

common-module/src/main/java/shop/bluebooktle/common/domain/point/PolicyType.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/admin/AdminPointPolicyController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/repository/AdminPointRepository.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/AdminPointService.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/AdminPointServiceImpl.java
frontend-server/src/main/resources/templates/admin/point/point_settings_form.html
frontend-server/src/main/resources/templates/admin/point/policy_form.html

- refs #271 
- 어드인 포인트 페이지 활성화 체크 안되던거 수정
-
-
-

[#271][FRONT][포인트] - 포인트 정책페이지 수정

---

backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/CategoryServiceImpl.java
backend-server/src/main/resources/initData.sql
backend-server/src/test/java/shop/bluebooktle/backend/book/jpa/CategoryRepositoryTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/CategoryServiceTest.java
frontend-server/src/main/resources/templates/_fragments/header.html

- closes #302 
- 카테고리 QueryDSL, Service 테스트 코드 작성
-
-
-

[#302][BACK][도서] - 카테고리 테스트 코드 작성 

---

frontend-server/src/main/resources/application-local.yml
frontend-server/src/main/resources/application.yml

- FE FeigntClient 요청 Eureka -> Gateway 라우트하도록 변경

[FE][Repository] - FeigntClient 요청 Eureka -> Gateway 라우트하도록 변경

---

.github/workflows/maven.yml
backend-server/http/publisher.http
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/admin/AdminPublisherController.java

fix(Front): change path

---

frontend-server/src/main/java/shop/bluebooktle/frontend/controller/admin/AdminCouponController.java
frontend-server/src/main/resources/templates/admin/coupon/book_list.html
frontend-server/src/main/resources/templates/admin/coupon/coupon_form.html

closes #48 
- 특정 도서, 카테고리에 해당하는 쿠폰 생성 구현
- issue #320 에서 rebase 중 다른 commit도 추가되어서 다시 브랜치 생성해서 PR 올렸습니다!
- http://localhost:9080/admin/coupons 에서 쿠폰 정책의 Target이 BOOK인 쿠폰 정책 선택

[#48][FRONT][쿠폰] - 도서 관련 쿠폰 생성

---

backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/AladinBookServiceImpl.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/AladinBookServiceTest.java
common-module/src/main/java/shop/bluebooktle/common/dto/book/request/AladinBookItem.java
common-module/src/main/java/shop/bluebooktle/common/dto/book/response/AladinApiResponse.java

- refs #324 
- AladinBookService 테스트 코드 작성 (100%)
- [Sonar Qube](http://s4.java21.net:9000/code?id=bluebooktle-local&selected=bluebooktle-local%3Abackend-server%2Fsrc%2Fmain%2Fjava%2Fshop%2Fbluebooktle%2Fbackend%2Fbook%2Fservice%2Fimpl)

[#324][BACK][TEST] - Sonar Qube Test Coverage 보강

---

backend-server/src/main/java/shop/bluebooktle/backend/coupon/controller/CouponController.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/controller/UserCouponController.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/CouponQueryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/impl/CouponQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/UserCouponService.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/UserCouponServiceImpl.java
backend-server/src/test/java/shop/bluebooktle/backend/coupon/jpa/CouponRepositoryTest.java
backend-server/src/test/java/shop/bluebooktle/backend/coupon/service/UserCouponServiceTest.java
common-module/src/main/java/shop/bluebooktle/common/domain/UserCouponFilterType.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/response/UserCouponResponse.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/myPage/MyPageController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/repository/CouponRepository.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/CouponService.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/CouponServiceImpl.java
frontend-server/src/main/resources/templates/admin/coupon/coupon_form.html
frontend-server/src/main/resources/templates/mypage/coupon_list.html

closes #237 
- MyPage에서 유저가 보유한 쿠폰을 필터 별 조회
- URL
http://localhost:9080/mypage/coupons

[#237][FRONT][쿠폰] - MyPage 쿠폰 조회

---

frontend-server/src/main/java/shop/bluebooktle/frontend/config/advice/GlobalCartCountAdvice.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/CartController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/repository/CartRepository.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/CartServiceImpl.java
frontend-server/src/main/resources/templates/book/book_detail.html

refs #240
- Controller에서 Redirect 처리 -> JS에서 처리
-
-
-

[#240][FIX][장바구니] cart load fix + 디버깅 로그 추가

---

auth-server/http/auth.http
backend-server/http/book.http
backend-server/src/main/java/shop/bluebooktle/backend/BackendServerApplication.java
backend-server/src/main/java/shop/bluebooktle/backend/order/entity/Order.java
backend-server/src/main/java/shop/bluebooktle/backend/order/repository/OrderQueryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/order/repository/OrderRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/impl/OrderServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/entity/Payment.java
backend-server/src/main/resources/schema.sql
common-module/src/main/java/shop/bluebooktle/common/domain/order/OrderStatus.java
common-module/src/main/java/shop/bluebooktle/common/dto/order/request/OrderCreateRequest.java
common-module/src/main/java/shop/bluebooktle/common/dto/order/response/OrderHistoryResponse.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/OrderController.java
frontend-server/src/main/resources/templates/mypage/order_list.html
frontend-server/src/main/resources/templates/order/create_form.html

[FRONT][주문] - 주문 내역 조회

---

backend-server/src/main/java/shop/bluebooktle/backend/cart/controller/CartController.java
backend-server/src/main/java/shop/bluebooktle/backend/cart/service/impl/CartServiceImpl.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/BookController.java

- 회원가입 시 Cart null이 반환되는 오류 수정
-
-
-

[#240][FIX][장바구니] : Cart null 반환 안하도록 수정

---

backend-server/http/aladinBook.http
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/ImageController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/repository/ImageServerClient.java
frontend-server/src/main/java/shop/bluebooktle/frontend/repository/ImgRepository.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/AdminBookServiceImpl.java

- FE 이미지 컨트롤러 구현
- FE 도서 등록 및 수정 서비스단에서 로직 수정 
-
-

[FIX][도서이미지] - 미니오 dev 서버 오류 해결

---

auth-server/pom.xml
auth-server/src/main/java/shop/bluebooktle/auth/config/DataSourceConfig.java
auth-server/src/main/resources/application-local.yml
backend-server/pom.xml
backend-server/src/main/java/shop/bluebooktle/backend/config/DataSourceConfig.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/entity/PaymentDetail.java
backend-server/src/main/resources/application-local.yml
pom.xml

- Hikari -> dbcp2 사용하도록 수정
- PaymentDetail key에 백틱 추가
- 서버 실행시 로그에 2025-06-09 10:15:36 [main] INFO  o.hibernate.orm.connections.pooling - HHH10001005: Database info:
Database JDBC URL [Connecting through datasource 'org.apache.commons.dbcp2.BasicDataSource@568fd3de'와 유사하게 나오면 적용된 것
-

[AUTH, BACK][DB] - dbcp2 사용

---

backend-server/src/main/java/shop/bluebooktle/backend/order/controller/OrderController.java
backend-server/src/main/java/shop/bluebooktle/backend/order/service/impl/OrderServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/payment/service/impl/PaymentServiceImpl.java
backend-server/src/main/resources/initData.sql
backend-server/src/main/resources/schema.sql
common-module/src/main/java/shop/bluebooktle/common/domain/order/OrderStatus.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/OrderController.java
frontend-server/src/main/resources/templates/_layouts/admin_layout.html
frontend-server/src/main/resources/templates/order/complete.html

- 비회원 주문 추가, 주문 상태(상품 준비중) 추가
-
-
-
-

[BACK, FRONT][주문] 비회원 주문 추가, 주문 상태(상품 준비중) 추가

---

frontend-server/src/main/java/shop/bluebooktle/frontend/controller/BookController.java
frontend-server/src/main/resources/templates/book/book_list.html

- 하드코딩된 필터링 개수 수정 및 정렬 요청을 보내는 form 태그 수정
-
-
-

[#18][FRONT][도서 목록 조회] - html 수정 및 FE 컨트롤러 수정

---

backend-server/src/main/java/shop/bluebooktle/backend/book/entity/BookCategory.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookCategoryServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookImgServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/user/service/impl/UserServiceImpl.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/AladinBookServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/BookAuthorServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/BookCategoryServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/BookImgServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/user/controller/AddressControllerTest.java
backend-server/src/test/java/shop/bluebooktle/backend/user/controller/AddressControllerUnitTest.java
backend-server/src/test/java/shop/bluebooktle/backend/user/service/AddressServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/user/service/RedisDormantAuthCodeServiceTest.java
backend-server/src/test/java/shop/bluebooktle/backend/user/service/UserServiceTest.java
common-module/src/main/java/shop/bluebooktle/common/dto/book/request/BookImgRegisterRequest.java
common-module/src/main/java/shop/bluebooktle/common/entity/auth/User.java
common-module/src/main/java/shop/bluebooktle/common/exception/ErrorCode.java
common-module/src/main/java/shop/bluebooktle/common/exception/user/AddressNotFoundException.java

- refs #324 
- AddressServiceTest 작성
- RedisDormantAuthCodeServiceTest 작성
- UserServiceTest 작성
- AddressControllerTest 작성
- [Sonar Qube](http://s4.java21.net:9000/code?id=bluebooktle-local&selected=bluebooktle-local%3Abackend-server%2Fsrc%2Fmain%2Fjava%2Fshop%2Fbluebooktle%2Fbackend%2Fuser%2Fservice%2Fimpl)

[#324][BACK][TEST] - user 테스트 코드 작성 (100%)

---

backend-server/src/main/java/shop/bluebooktle/backend/book/repository/CategoryQueryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/CategoryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/book/repository/impl/CategoryQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/BookCategoryService.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/CategoryService.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookCategoryServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/CategoryServiceImpl.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/CategoryServiceTest.java
frontend-server/src/main/java/shop/bluebooktle/frontend/config/advice/GlobalCategoryInfoAdvice.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/CategoryServiceImpl.java

- closes #402 
- 카테고리 등록 로직
- 카테고리 전체 조회 로직 (트리 구조) (EntityGraph 사용)
- 특정 카테고리의 하위 카테고리 조회 로직
- 관리자 페이지 카테고리 목록 페이징 조회 (EntityGraph 사용)
- 관리자 페이지 접근시 Redis에 저장된 카테고리 캐싱 조회 제외 처리 (GlobalCategoryInfoAdvice 클래스 수정)
-
-
-

[#402][BACK, FRONT][도서] - 카테고리 N+1 문제 해결 및 관리자 페이지 카테고리 캐싱 조회 제외 (100%)

---

backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/ReviewServiceImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/elasticsearch/service/BookElasticSearchService.java
backend-server/src/main/java/shop/bluebooktle/backend/elasticsearch/service/impl/BookElasticSearchServiceImpl.java
frontend-server/src/main/resources/templates/book/book_list.html

- closes #18
- 리뷰 등록 시 엘라스틱 정보 등록되도록 변경
-
-
-

[#18][BACK. FRONT][도서][VIEW] - 리뷰 등록 시 엘라스틱 정보 등록

---

backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/BookRegisterServiceImpl.java

fix(도서) - 알라딘 도서 등록 해상도 증가 로직 추가

---

backend-server/src/main/java/shop/bluebooktle/backend/order/controller/AdminOrderController.java
backend-server/src/main/java/shop/bluebooktle/backend/order/repository/impl/OrderQueryRepositoryImpl.java
common-module/src/main/java/shop/bluebooktle/common/dto/order/request/AdminOrderSearchRequest.java

- AdminOrderSearchRequest에서 기존 record -> class로 변경하고 setter추가
-
-

[Fix][COMMON][주문] - 주문 검색 필터 처리

---

backend-server/src/main/java/shop/bluebooktle/backend/book/repository/impl/CategoryQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/book/service/impl/CategoryServiceImpl.java
backend-server/src/test/java/shop/bluebooktle/backend/book/jpa/CategoryRepositoryTest.java
backend-server/src/test/java/shop/bluebooktle/backend/book/service/CategoryServiceTest.java

[#302][BACK][도서][테스트 추가] - 카테고리 테스트 코드

---

backend-server/src/test/java/shop/bluebooktle/backend/coupon/controller/UserCouponControllerTest.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/CouponController.java
frontend-server/src/test/java/shop/bluebooktle/frontend/controller/CouponControllerTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/controller/admin/AdminCouponControllerTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/controller/myPage/MyPageCouponControllerTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/AdminCouponServiceTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/CouponServiceTest.java

[Test][FRONT][쿠폰] - 쿠폰 Front TC 작성

---

common-module/src/main/java/shop/bluebooktle/common/dto/book/response/BookDetailResponse.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/BookController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/admin/AdminAuthorController.java
frontend-server/src/test/java/shop/bluebooktle/frontend/controller/BookControllerTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/controller/mypage/MyPageBookLikesControllerTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/BookServiceTest.java

- refs #441 
- FE : BookController, BookService 테스트 코드 완료
-
-

[#441][FRONT][도서][테스트] - FE 도서 테스트 코드 및 주석 삭제

---

frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/AdminBookServiceImpl.java
frontend-server/src/main/resources/templates/admin/aladin_book/aladin_book_form.html
frontend-server/src/main/resources/templates/admin/book/book_edit_form.html

- refs #406 
- 도서 등록, 수정시 태그 검색 및 페이지 옮겼을 때 도서 자동 등록 및 수정 되는 오류 발견해 수정함
- 기존의 이미지 파일 없이 수정이 안 되는 오류 해결
-
-
-

[#406][FRONT][도서][Serivce 및 View] - 도서 등록, 수정시 태그 오류 수정, 이미지 파일 없이도 수정 가능하도록 구현

---

backend-server/src/main/java/shop/bluebooktle/backend/elasticsearch/document/BookDocument.java
backend-server/src/main/java/shop/bluebooktle/backend/elasticsearch/repository/BookElasticSearchCustomRepository.java
backend-server/src/test/java/shop/bluebooktle/backend/elasticsearch/config/ElasticsearchConfigTest.java
backend-server/src/test/java/shop/bluebooktle/backend/elasticsearch/repository/BookElasticSearchCustomRepositoryTest.java
backend-server/src/test/java/shop/bluebooktle/backend/elasticsearch/service/BookElasticSearchServiceTest.java
backend-server/src/test/resources/application-test.yml
frontend-server/src/test/java/shop/bluebooktle/frontend/service/AdminAuthorServiceTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/AdminBookServiceTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/AdminCategoryServiceTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/AdminImgServiceTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/AdminPublisherServiceTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/AdminTagServiceTest.java
frontend-server/src/test/java/shop/bluebooktle/frontend/service/CategoryServiceTest.java

- #441 
- FE 도서 관련 테스트 작성
- BE 엘라스틱서치 관련 테스트 코드 작성
-
-
-

[#441][FRONT, BACK][도서, ELK][TEST] - 테스트 코드 작성 및 안 쓰는 메서드 정리 

---

backend-server/src/main/java/shop/bluebooktle/backend/coupon/controller/FailedCouponIssueController.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/dto/CouponIssueMessage.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/entity/FailedCouponIssue.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/mq/birthday/BirthdayCouponIssueListener.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/mq/failure/FailedCouponDlqListener.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/mq/failure/FailedCouponIssuePublisher.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/FailedCouponIssueQueryRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/FailedCouponIssueRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/UserCouponRepository.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/impl/CouponQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/impl/FailedCouponIssueQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/repository/impl/UserCouponQueryRepositoryImpl.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/FailedCouponIssueService.java
backend-server/src/main/java/shop/bluebooktle/backend/coupon/service/impl/FailedCouponIssueServiceImpl.java
backend-server/src/main/resources/schema.sql
common-module/src/main/java/shop/bluebooktle/common/domain/coupon/CouponIssueStatus.java
common-module/src/main/java/shop/bluebooktle/common/domain/coupon/CouponIssueType.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/request/FailedCouponIssueSearchRequest.java
common-module/src/main/java/shop/bluebooktle/common/dto/coupon/response/FailedCouponIssueResponse.java
common-module/src/main/java/shop/bluebooktle/common/exception/ErrorCode.java
common-module/src/main/java/shop/bluebooktle/common/exception/coupon/FailedCouponNotFoundException.java
frontend-server/src/main/java/shop/bluebooktle/frontend/controller/admin/AdminCouponController.java
frontend-server/src/main/java/shop/bluebooktle/frontend/repository/AdminCouponRepository.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/AdminCouponService.java
frontend-server/src/main/java/shop/bluebooktle/frontend/service/impl/AdminCouponServiceImpl.java
frontend-server/src/main/resources/templates/admin/coupon/coupon_list.html
frontend-server/src/main/resources/templates/admin/coupon/failed_coupon_list.html

refs #308 
- dlq에 저장되어 있는 메세지 failed_coupon_issue 테이블에 저장
- 테이블에 저장된 데이터를 다시 queue에 전송
- /admin/coupons/failed
-

[#308][BACK,FRONT][쿠폰] - mq 실패 시 처리 

---

backend-server/src/main/resources/application-local.yml
frontend-server/src/main/resources/static/css/styles.css

feat(ui/docs): change UI color, swagger path

---

backend-server/src/main/java/shop/bluebooktle/backend/config/SecurityConfig.java

[BACK][문서화] - Swagger 접근 수정
